default: &default
  adapter: mysql2
  encoding: utf8
  pool: 20
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: mylovenew

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default