default: &default
  adapter: mysql2
  encoding: utf8
  pool: 20
  host: 127.0.0.1
  port: 3306
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: mylovenew

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default